# Generated by Django 5.1.7 on 2025-06-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeeklyReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("StallID", models.IntegerField(verbose_name="档口ID")),
                ("StartDate", models.DateField(verbose_name="开始日期")),
                ("EndDate", models.DateField(verbose_name="结束日期")),
                ("TotalReviews", models.IntegerField(verbose_name="总评论数")),
                ("AverageRating", models.FloatField(verbose_name="平均评分")),
                ("HighRatingCount", models.IntegerField(verbose_name="好评数量")),
                ("MidRatingCount", models.IntegerField(verbose_name="中评数量")),
                ("LowRatingCount", models.IntegerField(verbose_name="差评数量")),
                (
                    "CommonKeywords",
                    models.TextField(blank=True, null=True, verbose_name="常见关键词"),
                ),
                (
                    "Suggestions",
                    models.TextField(blank=True, null=True, verbose_name="改进建议"),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
        ),
    ]
