# Generated by Django 5.1.7 on 2025-06-29 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weeklyreport",
            name="Suggestions",
        ),
    ]
