# Generated by Django 3.0 on 2025-06-23 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CanteenName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StallInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StallName', models.CharField(max_length=100)),
                ('Canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.CanteenInfo')),
            ],
        ),
        migrations.CreateModel(
            name='DishInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DishName', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.StallInfo')),
            ],
        ),
    ]
