# Generated by Django 3.0 on 2025-06-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteeninfo',
            name='CanteenName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stallinfo',
            name='StallName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
