# Generated by Django 5.2.3 on 2025-06-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reviews_count', models.IntegerField()),
                ('rating', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('specialties', models.CharField(max_length=255)),
            ],
        ),
    ]
