# Generated by Django 3.0 on 2025-06-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=32, verbose_name='用户名')),
                ('Password', models.CharField(max_length=20, verbose_name='密码')),
                ('UserType', models.IntegerField(verbose_name='用户类型')),
                ('StallID', models.IntegerField(verbose_name='档口ID')),
            ],
        ),
    ]
