# Generated by Django 3.0 on 2025-06-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='StallID',
            field=models.IntegerField(blank=True, null=True, verbose_name='档口ID'),
        ),
    ]
