# Generated by Django 3.0 on 2025-06-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0002_auto_20250624_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField(verbose_name='用户ID')),
                ('Username', models.CharField(max_length=40, verbose_name='用户名')),
                ('StallID', models.IntegerField(verbose_name='申请认证档口ID')),
                ('Describe', models.TextField(max_length=450, verbose_name='申请描述')),
                ('Validity', models.IntegerField(verbose_name='是否有效')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Username',
            field=models.CharField(max_length=40, verbose_name='用户名'),
        ),
    ]
