# Generated by Django 3.0 on 2025-06-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0003_auto_20250624_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Username',
            field=models.CharField(max_length=40, verbose_name='邮箱'),
        ),
    ]
