# Generated by Django 3.0 on 2025-06-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0004_auto_20250624_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authmessage',
            name='Describe',
            field=models.TextField(max_length=110, verbose_name='申请描述'),
        ),
        migrations.AlterField(
            model_name='authmessage',
            name='Username',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Username',
            field=models.CharField(max_length=20, verbose_name='邮箱'),
        ),
    ]
